### ISSUE TITLE
Symbol's value as variable is void: cider-cheatsheet-hierarchy

### ISSUE THREAD

**Issue by wusticality** [clojure-emacs/helm-cider#11]
Just updated `helm` and `cider` and I get the following warning when starting emacs:

`Error (use-package): helm-cider/:catch: Symbol’s value as variable is void: cider-cheatsheet-hierarchy`

It shows up in a buffer called `*Warnings*`.

Thanks, -it3ration

**Comment by xiongtx** [comment]
Forgot a `require`, thanks.

**Comment by wusticality** [comment]
Sure thing, thanks for the prompt fix!
