### ISSUE TITLE
helm-cider-spec is not overriding`cider`'s spec commands

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/helm-cider#3]
Unlike other `helm-cider` commands `helm-cider-spec` doesn't override `cider-browse-spec-all` and thus not activated by `(helm-cider-mode 1)`.

**Comment by xiongtx** [comment]
I can add `cider-browse-spec-all` to `helm-cider-overrides`, but there's no CIDER equivalent of `cider-browse-spec-ns` (unless @jpmonettas or someone else works on clojure-emacs/cider#2074).

**Comment by jpmonettas** [comment]
@vspinu There is still no way to create cider-browse-spec-ns, see de discussion in https://github.com/clojure-emacs/cider/issues/2163#issuecomment-357663035
