### ISSUE TITLE
Selection of vars within ns in helm-cider-spec-ns breaks on typing

### ISSUE THREAD

**Issue by vspinu** [clojure-emacs/helm-cider#5]
Enter `helm-cider-spec-ns` select your ns then type something. Filtering happens globally, not just within the selected ns.

**Comment by xiongtx** [comment]
Well, it's meant to filter globally, not within a single Helm source (spec namespace).

You can use `helm-show-all-in-this-source-only` (default `C-M-a`) to narrow to a single source, and `helm-display-all-sources` (default `C-M-e`) to widen again. Filters will then apply only to that Helm source. This is standard Helm functionality, not particular to `helm-cider`.

I considered applying the narrowing automatically after selecting the ns (for this and other applications), but found it confusing and not good UX.
